export enum ApplicationsEnum {
  ADMIN = 'ADMIN',
  SITE = 'SITE',
  PORTAL_MEMBER = 'PORTAL_MEMBER',
  CHURCH_MANAGER = 'CHURCH_MANAGER',
  EVENTS_CONTROLLER = 'EVENTS_CONTROLLER',
  EAD_ALUNO = 'EAD_ALUNO',
  EAD_PROFESSOR = 'EAD_PROFESSOR',
  EAD_ADMIN = 'EAD_ADMIN',
}